# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# misc
umask 0022
export GIT_SSL_NO_VERIFY=true

# source sciflo virtualenv if exists
export SCIFLO_DIR=$HOME/sciflo
if [ -e "$SCIFLO_DIR/bin/activate" ]; then
  source $SCIFLO_DIR/bin/activate
fi
